### ISSUE TITLE
Upcoming Events showing past events 

### ISSUE THREAD

**Issue by dineshkannan010** [SoftwareEngineeringNCSU101/BurnoutExtreme#2]
![image](https://github.com/user-attachments/assets/f030fa5a-1e7b-4e94-a042-2a311c420bad)

**Comment by Harshvardhan14** [comment]
![image](https://github.com/user-attachments/assets/3a4c4c76-7ad1-4cc1-b164-36bdefc44e22)

* Issue is resolved, only the event in the future are displayed under the upcoming event section.

**Comment by Harshvardhan14** [comment]
Closing in my branch. (hspatil)
