### ISSUE TITLE
Inaccessible Event Modal

### ISSUE THREAD

**Issue by dineshkannan010** [SoftwareEngineeringNCSU101/BurnoutExtreme#5]
When an event is clicked, two Modal pops up where one overlaps the other thus the first modal is not accessible at all.
![image](https://github.com/user-attachments/assets/1d414513-4650-46bf-954b-7bb3fe942781)

**Comment by SakshiPhatak** [comment]
The two modals have been combined into a single modal. The description and maps are combined in a single modal.
![WhatsApp Image 2024-11-26 at 16 21 18_02023cca](https://github.com/user-attachments/assets/b188b7a2-5020-48d9-bea6-fe74650fd3cd)
